GET http://localhost:8989/courses/

###

GET http://localhost:8989/courses/9dddb80a-9190-484a-80a8-22bbe0765dbc

###

POST http://localhost:8989/courses
content-type: application/json

{
    "name": "Curso 01",
    "description": "testando primeiro curso criado"
}

###

PUT http://localhost:8989/courses/9dddb80a-9190-484a-80a8-22bbe0765dbc
content-type: application/json

{
    "name": "Curso 01",
    "description": "Alterando a descrição do curso criado"
}

###

DELETE http://localhost:8989/courses/f12bfffc-846f-4b07-beaf-5b9c1e19bb09

###

GET http://localhost:8989/courses/9dddb80a-9190-484a-80a8-22bbe0765dbc/modules

###

POST http://localhost:8989/courses/9dddb80a-9190-484a-80a8-22bbe0765dbc/modules

content-type: application/json

{
   "course": "9dddb80a-9190-484a-80a8-22bbe0765dbc",
    "name": "EAD 01"

}
