GET http://localhost:8989/courses/

###

GET http://localhost:8989/courses/3572062c-3675-4a8f-a6b2-9f0616e2f1ea

###

POST http://localhost:8989/courses
content-type: application/json

{
    "name": "Curso 01",
    "description": "testando primeiro curso criado"
}

###

PUT http://localhost:8989/courses/3572062c-3675-4a8f-a6b2-9f0616e2f1ea
content-type: application/json

{
    "name": "Curso 01",
    "description": "Alterando a descrição do curso criado"
}

###

DELETE http://localhost:8989/courses/f12bfffc-846f-4b07-beaf-5b9c1e19bb09

###

GET http://localhost:8989/courses/3572062c-3675-4a8f-a6b2-9f0616e2f1ea/modules

###

POST http://localhost:8989/courses/3572062c-3675-4a8f-a6b2-9f0616e2f1ea/modules

content-type: application/json

{
   "course": "3572062c-3675-4a8f-a6b2-9f0616e2f1ea",
   "name": "EAD-01"

}
